/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUpdatesIndexRouteImport } from './routes/_authenticated/updates/index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedScheduleIndexRouteImport } from './routes/_authenticated/schedule/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedPrepIndexRouteImport } from './routes/_authenticated/prep/index'
import { Route as AuthenticatedNewsIndexRouteImport } from './routes/_authenticated/news/index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedGradesIndexRouteImport } from './routes/_authenticated/grades/index'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams/index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedAssignmentsIndexRouteImport } from './routes/_authenticated/assignments/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedActivitiesIndexRouteImport } from './routes/_authenticated/activities/index'
import { Route as AuthenticatedPrepAddLessonRouteImport } from './routes/_authenticated/prep/add-lesson'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpdatesIndexRoute =
  AuthenticatedUpdatesIndexRouteImport.update({
    id: '/updates/',
    path: '/updates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScheduleIndexRoute =
  AuthenticatedScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrepIndexRoute = AuthenticatedPrepIndexRouteImport.update({
  id: '/prep/',
  path: '/prep/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsIndexRoute = AuthenticatedNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGradesIndexRoute =
  AuthenticatedGradesIndexRouteImport.update({
    id: '/grades/',
    path: '/grades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsIndexRoute =
  AuthenticatedAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivitiesIndexRoute =
  AuthenticatedActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrepAddLessonRoute =
  AuthenticatedPrepAddLessonRouteImport.update({
    id: '/prep/add-lesson',
    path: '/prep/add-lesson',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/prep/add-lesson': typeof AuthenticatedPrepAddLessonRoute
  '/activities': typeof AuthenticatedActivitiesIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/assignments': typeof AuthenticatedAssignmentsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/grades': typeof AuthenticatedGradesIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/news': typeof AuthenticatedNewsIndexRoute
  '/prep': typeof AuthenticatedPrepIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/schedule': typeof AuthenticatedScheduleIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/updates': typeof AuthenticatedUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/prep/add-lesson': typeof AuthenticatedPrepAddLessonRoute
  '/activities': typeof AuthenticatedActivitiesIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/assignments': typeof AuthenticatedAssignmentsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/grades': typeof AuthenticatedGradesIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/news': typeof AuthenticatedNewsIndexRoute
  '/prep': typeof AuthenticatedPrepIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/schedule': typeof AuthenticatedScheduleIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/updates': typeof AuthenticatedUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/prep/add-lesson': typeof AuthenticatedPrepAddLessonRoute
  '/_authenticated/activities/': typeof AuthenticatedActivitiesIndexRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/assignments/': typeof AuthenticatedAssignmentsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/grades/': typeof AuthenticatedGradesIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/news/': typeof AuthenticatedNewsIndexRoute
  '/_authenticated/prep/': typeof AuthenticatedPrepIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/schedule/': typeof AuthenticatedScheduleIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/updates/': typeof AuthenticatedUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prep/add-lesson'
    | '/activities'
    | '/analytics'
    | '/assignments'
    | '/attendance'
    | '/exams'
    | '/grades'
    | '/messages'
    | '/news'
    | '/prep'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/students'
    | '/updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prep/add-lesson'
    | '/activities'
    | '/analytics'
    | '/assignments'
    | '/attendance'
    | '/exams'
    | '/grades'
    | '/messages'
    | '/news'
    | '/prep'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/students'
    | '/updates'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/prep/add-lesson'
    | '/_authenticated/activities/'
    | '/_authenticated/analytics/'
    | '/_authenticated/assignments/'
    | '/_authenticated/attendance/'
    | '/_authenticated/exams/'
    | '/_authenticated/grades/'
    | '/_authenticated/messages/'
    | '/_authenticated/news/'
    | '/_authenticated/prep/'
    | '/_authenticated/reports/'
    | '/_authenticated/schedule/'
    | '/_authenticated/settings/'
    | '/_authenticated/students/'
    | '/_authenticated/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/updates/': {
      id: '/_authenticated/updates/'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AuthenticatedUpdatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule/': {
      id: '/_authenticated/schedule/'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prep/': {
      id: '/_authenticated/prep/'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof AuthenticatedPrepIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news/': {
      id: '/_authenticated/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grades/': {
      id: '/_authenticated/grades/'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthenticatedGradesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments/': {
      id: '/_authenticated/assignments/'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities/': {
      id: '/_authenticated/activities/'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prep/add-lesson': {
      id: '/_authenticated/prep/add-lesson'
      path: '/prep/add-lesson'
      fullPath: '/prep/add-lesson'
      preLoaderRoute: typeof AuthenticatedPrepAddLessonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPrepAddLessonRoute: typeof AuthenticatedPrepAddLessonRoute
  AuthenticatedActivitiesIndexRoute: typeof AuthenticatedActivitiesIndexRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedAssignmentsIndexRoute: typeof AuthenticatedAssignmentsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedGradesIndexRoute: typeof AuthenticatedGradesIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedNewsIndexRoute: typeof AuthenticatedNewsIndexRoute
  AuthenticatedPrepIndexRoute: typeof AuthenticatedPrepIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedScheduleIndexRoute: typeof AuthenticatedScheduleIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedUpdatesIndexRoute: typeof AuthenticatedUpdatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPrepAddLessonRoute: AuthenticatedPrepAddLessonRoute,
  AuthenticatedActivitiesIndexRoute: AuthenticatedActivitiesIndexRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedAssignmentsIndexRoute: AuthenticatedAssignmentsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedGradesIndexRoute: AuthenticatedGradesIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedNewsIndexRoute: AuthenticatedNewsIndexRoute,
  AuthenticatedPrepIndexRoute: AuthenticatedPrepIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedScheduleIndexRoute: AuthenticatedScheduleIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedUpdatesIndexRoute: AuthenticatedUpdatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
